"""Canonical file names and column layouts for the drug-disease pipeline."""

CANONICAL_FILENAMES = {
    "ctd_therapeutic": "ctd_therapeutic.tsv",
    "drugbank_targets": "drugbank_targets.tsv",
    "disgenet_disease_proteins": "disgenet_disease_proteins.tsv",
    "biogrid_human_ppi": "biogrid_human_ppi.tsv",
    "biogrid_graph": "biogrid_graph.pkl",
    "pair_pathway_mapping": "pair_pathway_mapping.tsv",
    "subgraph_manifest": "subgraph_manifest.tsv",
    "predictions_raw": "predictions.tsv",
    "predictions_aggregated": "predictions_aggregated.tsv",
    "predictions_aggregated_all": "predictions_aggregated_all.tsv",
    "step05_report": "step05_report.json",
    "positive_pairs_self_loops": "positive_pairs_self_loops.tsv",
    "positive_pairs": "positive_pairs.tsv",
    "negative_pairs": "negative_pairs.tsv",
    "reactome_uniprot2AllPathways": "reactome_uniprot2AllPathways.tsv",
    "pair_pathway_mapping": "pair_pathway_mapping.tsv",
    "negative_pair_pathway_mapping": "negative_pair_pathway_mapping.tsv",
}

CANONICAL_COLUMNS = {
    "drug_disease_positives": [
        "DrugName",
        "DrugBankID",
        "DiseaseName",
        "DiseaseID",
        "Label",
    ],
    "drug_targets": [
        "DrugBankID",
        "DrugName",
        "TargetUniProtID",
        "Action",
    ],
    "disease_proteins": [
        "DiseaseName",
        "DiseaseID",
        "GeneSymbol",
        "UniProtID",
        "Score",
    ],
    "pair_level_positives": [
        "DrugName",
        "DrugBankID",
        "DiseaseName",
        "DiseaseID",
        "DrugTarget_UniProt",
        "DiseaseProtein_UniProt",
        "Label",
    ],
    "pair_pathway_mapping": [
        "DrugTarget_UniProt",
        "DiseaseProtein_UniProt",
        "PathwayID",
        "PathwayName",
        "NumParticipants",
        "ExperimentType",
        "BridgeNeeded",
        "Source",
        "EvidenceTier",
        "Participants",
    ],
    "subgraph_manifest": [
        "SubgraphID",
        "DrugTarget_UniProt",
        "DiseaseProtein_UniProt",
        "PathwayID",
        "PathwayName",
        "ExperimentType",
        "BridgeNeeded",
        "BridgeExtended",
        "ConnectivityExtended",
        "NumNodes",
        "NumEdges",
        "SubgraphPath",
    ],
    "predictions_raw": [
        "SubgraphID",
        "DrugTarget_UniProt",
        "DiseaseProtein_UniProt",
        "PathwayID",
        "PathwayName",
        "Score_Sigmoid",
        "Score_FoldStd",
        "Score_FoldRange",
        "Score_PathwayNormalized",
        "ExperimentType",
    ],
    "predictions_aggregated": [
        "DrugName",
        "DiseaseName",
        "DrugTarget_UniProt",
        "DiseaseProtein_UniProt",
        "NumPathways",
        "MeanScore",
        "MaxScore",
        "MeanPathwayNormalizedScore",
        "MaxPathwayNormalizedScore",
        "Label",
        "ExperimentType",
        "MeanScoreFoldStd",
        "MaxScoreFoldStd",
        "MeanScoreFoldRange",
        "MaxScoreFoldRange",
    ],
    "predictions_aggregated_all": [
        "DrugName",
        "DiseaseName",
        "DrugTarget_UniProt",
        "DiseaseProtein_UniProt",
        "NumPathways",
        "MeanScore",
        "MaxScore",
        "MeanPathwayNormalizedScore",
        "MaxPathwayNormalizedScore",
        "Label",
        "ExperimentType",
        "MeanScoreFoldStd",
        "MaxScoreFoldStd",
        "MeanScoreFoldRange",
        "MaxScoreFoldRange",
    ],
    "mapping_drug_diseases_uniprot": [
        'DrugTarget_UniProt',
        'DiseaseProtein_UniProt',
    ],
    "pair_source_aggregation": [
        'DrugTarget_UniProt',
        'DiseaseProtein_UniProt',
        'Source',
        'EvidenceTier',
    ],
    "reactome_db_col_names": [
        "UniProtID", 
        "PathwayID", 
        "URL", 
        "PathwayName", 
        "EvidenceCode", 
        "Species",
    ]
}
